### ISSUE TITLE
Error. Maya can't find module

### ISSUE THREAD

**Issue by Rammad27** [thejoltjoker/ChatGPTforMaya#1]
Clicking Autoload for the ChatGPT plugin from the Maya _plug-in manager_. It gives me an error stating, "_line 1: No module named 'chatgpt4maya'_" I found the module named **chatgptformaya** and changed it to **chatgpt4maya**, which made no difference. It's in the correct location. I've restarted Maya multiple times with no luck. I've attached a screenshot as well for better understanding. 
This error happens in both 2024 and 2023. 
<img width="1916" alt="error" src="https://github.com/thejoltjoker/ChatGPTforMaya/assets/123601034/f8d28079-749c-409d-ab7c-9e15e4cd5e43">

**Comment by thejoltjoker** [comment]
Do you have the repo in your PYTHONPATH?
