### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by art13eck** [thejoltjoker/ChatGPTforMaya#2]
Why is it so difficult

print( "root : Sending message \"hello\"\n" );
root : Sending message "hello"
error -noContext "root : \n\nYou tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.\n\nYou can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. \n\nAlternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`\n\nA detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742\n";
// Error: root : 
// 
// You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
// 
// You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 
// 
// Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
// 
// A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by art13eck** [comment]
install 0.27 and 0.28
root : Sending message "create cube"
nothing else happens

**Comment by thejoltjoker** [comment]
Thank you for reporting this issue, it seems like they have updated the api. I will have to upgrade when I get a chance.

**Comment by thejoltjoker** [comment]
I have now migrated openai using their instructions. I'm unable to try it at this moment though, but it should work.
